### ISSUE TITLE
Feature Request: Lighnting detection

### ISSUE THREAD

**Issue by xannor** [briis/pymeteobridgeio#1]
I noticed your template does not request/include lightning data. I was wondering if you could add support for it. I just recently added an ecowitt detector to my setup, but I missed the recent storms in my area so I dont have any strikes recorded yet. I did the request here since it seems your HACS component relys on this lib to get the data structure.

**Comment by briis** [comment]
Hi @xannor 
Yes, I can definitely do that. We have access to this data:
* lgt0dist: Distance to lightning in kilometer.
* lgt0energy: Energy of lightning strike (no physical unit).
* lgt0total: Number of lightning strokes.

Unless you have other wishes, I will do the number of Lightning Strokes for the current day, and the Energy and Distance for the last recorded strike.

**Comment by briis** [comment]
Hi again @xannor,
I just released version 2.1, which includes the lightning sensor. Re-Open this issue if you need more data than what I added with that release.

**Comment by xannor** [comment]
Thanks for the quick turnaround, once I get some strikes we'll see how well it does.
