### ISSUE TITLE
Feature Request: Addtitional temp/humidity

### ISSUE THREAD

**Issue by xannor** [briis/pymeteobridgeio#3]
I'm adding this as a separate request because this might be more complicated. I have two additional outdoor temp/humid sensors on my system and I was wondering if it would be possible to add them to the output? I understand if this may not be something you want to necessarily support.

**Comment by briis** [comment]
The way I am doing it, is that I supply a 0 in value if the sensor is not found, so it should not disrupt the system for anyone else. Can I assume your sensors are called `th1temp`, `th1hum`, `th2temp` and `th2hum` ?

**Comment by xannor** [comment]
the meteobridge also exports a th*dew and a th*heatindex for each "extra" sensor. Maybe instead of just adding it, an additional config option is added to denote the number of additional temp sensors, since that is something unique to a persons setup. I checked the template system and I do not think there is a way to detect how many there cold be as it is dependent on the provider meteobridge is using.

**Comment by briis** [comment]
It is definitely possible, but gets a bit more complex this way. I have a few other projects right now, but I will look in to this as soon as time permits.

**Comment by briis** [comment]
Hi @xannor 
I have just released V2.4 of the Meteobridge Integration. This adds support for these extra sensors. As I don't have any, I can't really check if it is working. So please let me know once you testet it. Please note, after the upgrade, you need to go to the Integrations page and change the number of Extra Sensors from 0 to 2 (If that is what you have) before it has any effect.

**Comment by xannor** [comment]
I just got it re-installed (not because of anything you had done, just moved the install to different hardware.) and IT seems to be picking up the additional sensors correctly. I don't know about other setups, but the GW1000 supports up to 8 temp sensors, so you can probably (and safely) increase the slider to a higher max and it would up to the end user to pick the right number. Also there could be other sensors (like soil, etc) so you might want to specify that the slide is for additional temp sensors, to be clear. Otherwise, I say it is working and thanks!

**Comment by briis** [comment]
Glad that it works and solves your specific situation.
For now I will leave it as is, as I have not received any other requests on this. But thanks for the suggestion.
I will close this Issue now.
